# Generated by Django 3.1.1 on 2020-10-14 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='pass1',
        ),
    ]
