# Generated by Django 3.1.1 on 2020-10-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201014_2201'),
    
    ]
