# Generated by Django 3.1.1 on 2020-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('catergory', models.CharField(max_length=20)),
                ('subcategory', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('contact', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
