# Generated by Django 3.1.1 on 2020-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product_upload',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
