# Generated by Django 3.1.1 on 2020-12-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201205_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_upload',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
